export type PricingType = "free" | "freemium" | "paid";

export interface PricingPlan {
  name: string;
  price: string;
  features: string[];
  highlighted?: boolean;
}

export interface Tool {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  category: string;
  tags: string[];
  url: string;
  pricing: PricingType;
  plans: PricingPlan[];
  featured: boolean;
  logo: string;
  addedAt: string;
}

export const CATEGORIES = [
  { id: "all", label: "전체" },
  { id: "writing", label: "글쓰기" },
  { id: "image", label: "이미지" },
  { id: "coding", label: "코딩" },
  { id: "productivity", label: "생산성" },
  { id: "video", label: "비디오" },
  { id: "audio", label: "오디오" },
  { id: "chatbot", label: "챗봇" },
  { id: "research", label: "리서치" },
  { id: "design", label: "디자인" },
  { id: "automation", label: "자동화" },
];

export const TOOLS: Tool[] = [
  {
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "OpenAI의 가장 강력한 대화형 AI",
    description:
      "ChatGPT는 OpenAI가 만든 대화형 AI로, 글쓰기, 코딩, 분석, 번역 등 다양한 작업을 자연어로 처리할 수 있습니다. GPT-4o 모델을 기반으로 이미지 분석, 파일 첨부, 웹 검색도 지원합니다.",
    category: "chatbot",
    tags: ["GPT-4", "대화", "글쓰기", "코딩", "분석"],
    url: "https://chatgpt.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["GPT-4o 제한 사용", "웹 검색", "이미지 업로드"] },
      { name: "Plus", price: "$20/월", features: ["GPT-4o 무제한", "GPT-o1 접근", "DALL·E 이미지 생성", "파일 분석"], highlighted: true },
      { name: "Team", price: "$30/월·인", features: ["Plus 기능 전체", "팀 관리 콘솔", "데이터 학습 제외"] },
    ],
    featured: true,
    logo: "🤖",
    addedAt: "2024-01-01",
  },
  {
    slug: "claude",
    name: "Claude",
    tagline: "Anthropic의 안전하고 강력한 AI 어시스턴트",
    description:
      "Claude는 Anthropic이 개발한 AI 어시스턴트로, 긴 문서 분석, 코드 작성, 창의적 글쓰기에 특히 강합니다. 최대 200K 토큰의 컨텍스트 윈도우를 지원해 긴 문서도 한번에 처리할 수 있습니다.",
    category: "chatbot",
    tags: ["Claude 3", "대화", "분석", "코딩", "안전성"],
    url: "https://claude.ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["Claude Sonnet 제한 사용", "파일 첨부", "프로젝트 기능"] },
      { name: "Pro", price: "$20/월", features: ["Claude 3.5 Sonnet/Opus 우선 접근", "5배 많은 사용량", "Projects 무제한"], highlighted: true },
    ],
    featured: true,
    logo: "✨",
    addedAt: "2024-01-02",
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    tagline: "최고 품질의 AI 이미지 생성 도구",
    description:
      "Midjourney는 텍스트 프롬프트로 고품질 이미지를 생성하는 AI 도구입니다. 예술적인 스타일부터 사실적인 이미지까지 다양한 스타일을 지원하며, Discord 기반으로 운영됩니다.",
    category: "image",
    tags: ["이미지 생성", "아트", "디자인", "Discord"],
    url: "https://midjourney.com",
    pricing: "paid",
    plans: [
      { name: "Basic", price: "$10/월", features: ["200장/월 생성", "상업적 사용 가능", "Discord 접근"] },
      { name: "Standard", price: "$30/월", features: ["15시간 Fast 모드", "Relax 모드 무제한", "동시 3개 작업"], highlighted: true },
      { name: "Pro", price: "$60/월", features: ["30시간 Fast 모드", "Stealth 모드(비공개)", "동시 12개 작업"] },
    ],
    featured: true,
    logo: "🎨",
    addedAt: "2024-01-03",
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    tagline: "AI 기반 코드 자동완성 및 페어 프로그래밍",
    description:
      "GitHub Copilot은 OpenAI Codex를 기반으로 한 AI 코딩 어시스턴트입니다. VS Code, JetBrains 등 주요 IDE에서 코드 자동완성, 함수 생성, 버그 수정을 지원합니다.",
    category: "coding",
    tags: ["코딩", "자동완성", "VS Code", "IDE", "GitHub"],
    url: "https://github.com/features/copilot",
    pricing: "paid",
    plans: [
      { name: "Individual", price: "$10/월", features: ["코드 자동완성", "채팅 기능", "CLI 지원"], highlighted: true },
      { name: "Business", price: "$19/월·인", features: ["Individual 전체", "조직 정책 관리", "감사 로그"] },
    ],
    featured: true,
    logo: "💻",
    addedAt: "2024-01-04",
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "Notion에 내장된 AI 글쓰기 어시스턴트",
    description:
      "Notion AI는 노션 워크스페이스에 통합된 AI 도구로, 문서 요약, 글쓰기, 번역, 아이디어 생성을 지원합니다. 기존 Notion 사용자라면 추가 설치 없이 바로 사용 가능합니다.",
    category: "productivity",
    tags: ["노션", "글쓰기", "요약", "번역", "생산성"],
    url: "https://notion.so/product/ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["AI 20회 체험", "기본 노션 기능"] },
      { name: "Plus + AI", price: "$16/월", features: ["AI 무제한", "무제한 블록", "파일 업로드 무제한"], highlighted: true },
    ],
    featured: false,
    logo: "📝",
    addedAt: "2024-01-05",
  },
  {
    slug: "runway",
    name: "Runway",
    tagline: "AI 기반 동영상 생성 및 편집",
    description:
      "Runway는 텍스트나 이미지로 동영상을 생성하고 편집할 수 있는 AI 플랫폼입니다. Gen-2 모델로 고품질 영상 생성, 배경 제거, 모션 브러시 등 다양한 기능을 제공합니다.",
    category: "video",
    tags: ["동영상", "영상 생성", "편집", "Gen-2"],
    url: "https://runwayml.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["125 크레딧 제공", "Gen-3 Alpha 접근", "최대 5초 영상"] },
      { name: "Standard", price: "$15/월", features: ["625 크레딧/월", "최대 16초 영상", "워터마크 없음"], highlighted: true },
      { name: "Pro", price: "$35/월", features: ["2250 크레딧/월", "최대 16초 영상", "4K 내보내기"] },
    ],
    featured: false,
    logo: "🎬",
    addedAt: "2024-01-06",
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "가장 자연스러운 AI 음성 생성",
    description:
      "ElevenLabs는 텍스트를 매우 자연스러운 음성으로 변환하는 AI 도구입니다. 목소리 복제, 다국어 지원, 감정 표현이 가능하며, 팟캐스트, 오디오북, 동영상 더빙에 활용됩니다.",
    category: "audio",
    tags: ["음성 합성", "TTS", "목소리 복제", "다국어"],
    url: "https://elevenlabs.io",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 10,000자", "목소리 3개 생성", "영어 등 기본 언어"] },
      { name: "Starter", price: "$5/월", features: ["월 30,000자", "목소리 10개 생성", "상업적 사용"], highlighted: true },
      { name: "Creator", price: "$22/월", features: ["월 100,000자", "목소리 30개", "Professional 복제"] },
    ],
    featured: false,
    logo: "🎙️",
    addedAt: "2024-01-07",
  },
  {
    slug: "perplexity",
    name: "Perplexity AI",
    tagline: "AI 기반 실시간 검색 엔진",
    description:
      "Perplexity AI는 인터넷을 실시간으로 검색해 출처와 함께 정확한 답변을 제공하는 AI 검색 엔진입니다. 학술 논문, 최신 뉴스, 전문 지식을 빠르게 리서치할 수 있습니다.",
    category: "research",
    tags: ["검색", "리서치", "실시간", "출처", "학술"],
    url: "https://perplexity.ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["무제한 검색", "GPT-4o Mini 기반", "파일 업로드 3개/일"] },
      { name: "Pro", price: "$20/월", features: ["Pro Search 300회/일", "GPT-4o·Claude 선택", "파일 업로드 무제한"], highlighted: true },
    ],
    featured: false,
    logo: "🔍",
    addedAt: "2024-01-08",
  },
  {
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    tagline: "오픈소스 AI 이미지 생성 모델",
    description:
      "Stable Diffusion은 무료 오픈소스 이미지 생성 AI입니다. 로컬에서 무제한으로 실행하거나 다양한 웹 서비스를 통해 사용할 수 있으며, 커스터마이징이 매우 자유롭습니다.",
    category: "image",
    tags: ["오픈소스", "이미지 생성", "무료", "로컬"],
    url: "https://stability.ai",
    pricing: "free",
    plans: [
      { name: "무료(로컬)", price: "완전 무료", features: ["무제한 이미지 생성", "상업적 사용 가능", "커스터마이징 자유", "GPU 필요"], highlighted: true },
      { name: "DreamStudio(클라우드)", price: "크레딧 구매", features: ["로컬 설치 불필요", "500장 기본 제공", "최신 모델 접근"] },
    ],
    featured: false,
    logo: "🖼️",
    addedAt: "2024-01-09",
  },
  {
    slug: "cursor",
    name: "Cursor",
    tagline: "AI 네이티브 코드 에디터",
    description:
      "Cursor는 AI가 깊이 통합된 VS Code 기반 코드 에디터입니다. 자연어로 코드 작성, 버그 수정, 코드베이스 전체를 이해하는 채팅 기능을 제공하며, 개발 생산성을 크게 향상시킵니다.",
    category: "coding",
    tags: ["코딩", "IDE", "에디터", "VS Code", "AI 코딩"],
    url: "https://cursor.sh",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["2주 Pro 체험", "이후 50회 느린 요청/월", "기본 자동완성"] },
      { name: "Pro", price: "$20/월", features: ["500회 빠른 요청/월", "무제한 느린 요청", "Claude·GPT-4 선택"], highlighted: true },
      { name: "Business", price: "$40/월·인", features: ["Pro 전체", "중앙 결제 관리", "사용 분석"] },
    ],
    featured: true,
    logo: "⚡",
    addedAt: "2024-01-10",
  },
  {
    slug: "gemini",
    name: "Gemini",
    tagline: "Google의 멀티모달 AI 어시스턴트",
    description:
      "Gemini는 Google이 개발한 멀티모달 AI로, 텍스트, 이미지, 코드, 오디오를 동시에 처리할 수 있습니다. Google 검색, Gmail, Docs 등 Google 서비스와 깊이 통합되어 있습니다.",
    category: "chatbot",
    tags: ["Google", "멀티모달", "검색", "대화", "이미지"],
    url: "https://gemini.google.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["Gemini 1.5 Flash", "이미지 분석", "Google 앱 연동"] },
      { name: "Advanced", price: "$19.99/월", features: ["Gemini 1.5 Pro Ultra", "2TB Google One 포함", "Gmail·Docs 심층 연동"], highlighted: true },
    ],
    featured: false,
    logo: "💎",
    addedAt: "2024-01-11",
  },
  {
    slug: "kling-ai",
    name: "Kling AI",
    tagline: "고품질 AI 동영상 생성",
    description:
      "Kling AI는 Kuaishou가 개발한 AI 동영상 생성 도구로, 텍스트와 이미지로 최대 2분 길이의 고품질 영상을 생성할 수 있습니다. 영화 수준의 화질과 자연스러운 움직임이 특징입니다.",
    category: "video",
    tags: ["동영상", "영상 생성", "AI 비디오"],
    url: "https://klingai.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["일 66 크레딧", "최대 5초 영상", "워터마크 포함"] },
      { name: "Standard", price: "$10/월", features: ["660 크레딧/월", "최대 10초 영상", "워터마크 없음"], highlighted: true },
      { name: "Pro", price: "$35/월", features: ["3000 크레딧/월", "최대 2분 영상", "상업적 사용"] },
    ],
    featured: false,
    logo: "🎥",
    addedAt: "2024-01-12",
  },
  {
    slug: "suno",
    name: "Suno",
    tagline: "텍스트로 완성된 음악을 만드는 AI",
    description:
      "Suno는 짧은 텍스트 프롬프트만으로 보컬과 악기가 포함된 완성된 음악을 생성하는 AI입니다. 장르, 분위기, 가사를 지정하면 수 초 만에 고품질 음원을 만들어줍니다.",
    category: "audio",
    tags: ["음악 생성", "작곡", "AI 음악", "보컬"],
    url: "https://suno.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["하루 50 크레딧", "비상업적 사용", "곡 공개 저장"] },
      { name: "Pro", price: "$10/월", features: ["2500 크레딧/월", "상업적 사용 가능", "비공개 생성"], highlighted: true },
      { name: "Premier", price: "$30/월", features: ["10,000 크레딧/월", "우선 생성 처리", "최대 4분 곡"] },
    ],
    featured: false,
    logo: "🎵",
    addedAt: "2024-01-13",
  },
  {
    slug: "v0",
    name: "v0 by Vercel",
    tagline: "텍스트로 UI 컴포넌트를 즉시 생성",
    description:
      "v0는 Vercel이 만든 AI UI 생성 도구로, 자연어 설명만으로 React + Tailwind CSS 컴포넌트를 즉시 생성합니다. shadcn/ui 기반으로 실제 프로덕션에 바로 사용 가능한 코드를 제공합니다.",
    category: "coding",
    tags: ["UI 생성", "React", "Tailwind", "Vercel", "컴포넌트"],
    url: "https://v0.dev",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 200 크레딧", "퍼블릭 프로젝트", "기본 컴포넌트 생성"] },
      { name: "Premium", price: "$20/월", features: ["월 5,000 크레딧", "프라이빗 프로젝트", "우선 생성"], highlighted: true },
    ],
    featured: false,
    logo: "🧩",
    addedAt: "2024-01-14",
  },
  {
    slug: "leonardo-ai",
    name: "Leonardo AI",
    tagline: "게임·디자인 특화 AI 이미지 생성",
    description:
      "Leonardo AI는 게임 에셋, 캐릭터 디자인, 콘셉트 아트에 특화된 AI 이미지 생성 플랫폼입니다. 다양한 파인튜닝 모델과 일관된 캐릭터 유지 기능이 강점입니다.",
    category: "image",
    tags: ["이미지 생성", "게임 에셋", "캐릭터", "콘셉트 아트"],
    url: "https://leonardo.ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["일 150 토큰", "기본 모델 접근", "퍼블릭 생성"] },
      { name: "Apprentice", price: "$12/월", features: ["월 8,500 토큰", "프라이빗 생성", "우선 처리"], highlighted: true },
      { name: "Artisan", price: "$30/월", features: ["월 25,000 토큰", "캐릭터 일관성", "실시간 생성"] },
    ],
    featured: false,
    logo: "🦁",
    addedAt: "2024-01-15",
  },
  {
    slug: "heygen",
    name: "HeyGen",
    tagline: "AI 아바타로 동영상 제작",
    description:
      "HeyGen은 실제 사람처럼 말하는 AI 아바타 동영상을 만드는 플랫폼입니다. 텍스트만 입력하면 다국어 립싱크 영상을 자동 생성하며, 마케팅·교육·유튜브 콘텐츠 제작에 많이 쓰입니다.",
    category: "video",
    tags: ["AI 아바타", "립싱크", "동영상", "마케팅", "다국어"],
    url: "https://heygen.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["영상 1개 체험", "워터마크 포함", "기본 아바타"] },
      { name: "Creator", price: "$29/월", features: ["월 15분 영상", "워터마크 없음", "아바타 5개"], highlighted: true },
      { name: "Business", price: "$89/월", features: ["월 30분 영상", "커스텀 아바타", "팀 협업"] },
    ],
    featured: false,
    logo: "🧑‍💻",
    addedAt: "2024-01-16",
  },
  {
    slug: "grok",
    name: "Grok",
    tagline: "xAI의 실시간 정보 기반 AI 어시스턴트",
    description:
      "Grok은 Elon Musk의 xAI가 개발한 AI로, X(트위터) 실시간 데이터에 접근할 수 있어 최신 트렌드와 뉴스에 대한 답변이 강점입니다. 유머러스한 답변 스타일도 특징입니다.",
    category: "chatbot",
    tags: ["실시간", "X", "트위터", "뉴스", "대화"],
    url: "https://grok.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["Grok 2 기본 접근", "X 실시간 검색", "이미지 생성 10회/일"] },
      { name: "X Premium+", price: "$16/월", features: ["Grok 2 무제한", "이미지 생성 무제한", "X 광고 제거"], highlighted: true },
    ],
    featured: false,
    logo: "⚡",
    addedAt: "2024-01-17",
  },
  {
    slug: "ideogram",
    name: "Ideogram",
    tagline: "텍스트 렌더링에 강한 AI 이미지 생성",
    description:
      "Ideogram은 이미지 안에 텍스트를 정확하게 렌더링하는 데 특화된 AI 이미지 생성 도구입니다. 로고, 포스터, 배너 디자인처럼 글자가 포함된 이미지 제작에 탁월합니다.",
    category: "image",
    tags: ["이미지 생성", "텍스트 렌더링", "로고", "포스터", "디자인"],
    url: "https://ideogram.ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["일 10회 생성", "퍼블릭 저장", "기본 해상도"] },
      { name: "Basic", price: "$8/월", features: ["월 400 크레딧", "프라이빗 생성", "고해상도"], highlighted: true },
      { name: "Plus", price: "$20/월", features: ["월 1,000 크레딧", "우선 처리", "상업적 사용"] },
    ],
    featured: false,
    logo: "🖋️",
    addedAt: "2024-01-18",
  },
  {
    slug: "descript",
    name: "Descript",
    tagline: "텍스트 편집으로 동영상·팟캐스트 편집",
    description:
      "Descript는 영상을 텍스트처럼 편집할 수 있는 혁신적인 도구입니다. 자동 자막 생성, 특정 단어 삭제 시 해당 구간 영상 자동 제거, AI 목소리 복제 기능을 제공합니다.",
    category: "video",
    tags: ["동영상 편집", "팟캐스트", "자막", "목소리 복제"],
    url: "https://descript.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 1시간 전사", "워터마크 포함", "기본 편집"] },
      { name: "Hobbyist", price: "$24/월", features: ["월 10시간 전사", "워터마크 없음", "4K 내보내기"], highlighted: true },
      { name: "Creator", price: "$40/월", features: ["월 30시간 전사", "목소리 복제 기능", "팀 협업"] },
    ],
    featured: false,
    logo: "✂️",
    addedAt: "2024-01-19",
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    tagline: "마케팅 카피를 자동으로 작성",
    description:
      "Copy.ai는 광고 문구, 이메일, SNS 포스트, 제품 설명 등 마케팅 카피를 AI로 자동 생성하는 도구입니다. 90개 이상의 템플릿과 25개 이상의 언어를 지원합니다.",
    category: "writing",
    tags: ["카피라이팅", "마케팅", "이메일", "SNS", "광고"],
    url: "https://copy.ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 2,000 단어", "90개 이상 템플릿", "25개 언어"] },
      { name: "Pro", price: "$49/월", features: ["단어 무제한", "5개 워크스페이스", "우선 지원"], highlighted: true },
    ],
    featured: false,
    logo: "✍️",
    addedAt: "2024-01-20",
  },
  {
    slug: "replit",
    name: "Replit",
    tagline: "브라우저에서 바로 코딩하고 배포",
    description:
      "Replit은 브라우저 기반 AI 코딩 환경으로, 자연어로 앱을 만들고 즉시 배포까지 할 수 있습니다. Replit Agent가 요구사항을 이해해 코드를 자동 생성하고 실행합니다.",
    category: "coding",
    tags: ["코딩", "브라우저", "배포", "AI 에이전트", "풀스택"],
    url: "https://replit.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["퍼블릭 프로젝트 무제한", "기본 AI 자동완성", "클라우드 실행"] },
      { name: "Core", price: "$25/월", features: ["프라이빗 프로젝트", "Replit Agent 접근", "항상 켜진 앱"], highlighted: true },
    ],
    featured: false,
    logo: "🔁",
    addedAt: "2024-01-21",
  },
  {
    slug: "otter-ai",
    name: "Otter.ai",
    tagline: "회의를 자동으로 기록하고 요약",
    description:
      "Otter.ai는 회의, 강의, 인터뷰를 실시간으로 전사하고 AI가 핵심 내용을 요약해주는 도구입니다. Zoom, Google Meet, Microsoft Teams와 연동되어 자동으로 회의록을 생성합니다.",
    category: "productivity",
    tags: ["전사", "회의록", "요약", "Zoom", "실시간"],
    url: "https://otter.ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 300분 전사", "AI 요약 30회", "Zoom 연동"] },
      { name: "Pro", price: "$16.99/월", features: ["월 1,200분 전사", "AI 요약 무제한", "고급 검색"], highlighted: true },
      { name: "Business", price: "$40/월", features: ["월 6,000분 전사", "팀 관리", "CRM 연동"] },
    ],
    featured: false,
    logo: "🦦",
    addedAt: "2024-01-22",
  },

  // ── 챗봇 ──────────────────────────────────────────────────────────────
  {
    slug: "deepseek",
    name: "DeepSeek",
    tagline: "중국발 초저가 고성능 추론 AI",
    description: "DeepSeek은 중국 AI 스타트업이 개발한 LLM으로, GPT-4 수준의 성능을 매우 저렴한 비용으로 제공합니다. DeepSeek-R1 모델은 복잡한 수학·코딩 추론에서 세계 최고 수준을 기록했으며, API 가격이 OpenAI 대비 최대 96% 저렴합니다.",
    category: "chatbot",
    tags: ["추론", "오픈소스", "저가격", "수학", "코딩"],
    url: "https://chat.deepseek.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["DeepSeek-V3 무제한", "웹 검색", "파일 업로드"] },
      { name: "API", price: "$0.14/M 토큰", features: ["DeepSeek-R1 접근", "초저가 가격", "OpenAI 호환 API"], highlighted: true },
    ],
    featured: false,
    logo: "🐋",
    addedAt: "2024-02-01",
  },
  {
    slug: "microsoft-copilot",
    name: "Microsoft Copilot",
    tagline: "Microsoft 365와 완전 통합된 AI 어시스턴트",
    description: "Microsoft Copilot은 GPT-4o 기반의 AI로 Word, Excel, PowerPoint, Outlook 등 Microsoft 365 앱과 깊이 통합됩니다. 문서 초안 작성, 데이터 분석, 이메일 요약 등을 자연어로 처리할 수 있습니다.",
    category: "chatbot",
    tags: ["Microsoft", "Office", "Word", "Excel", "GPT-4"],
    url: "https://copilot.microsoft.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["GPT-4o 기본 사용", "이미지 생성", "웹 검색"] },
      { name: "Pro", price: "$20/월", features: ["Microsoft 365 완전 통합", "우선 접근", "이미지 생성 무제한"], highlighted: true },
    ],
    featured: false,
    logo: "🪟",
    addedAt: "2024-02-02",
  },
  {
    slug: "meta-ai",
    name: "Meta AI",
    tagline: "Meta의 무료 AI 어시스턴트",
    description: "Meta AI는 Llama 4 모델 기반의 완전 무료 AI 어시스턴트입니다. Instagram, WhatsApp, Facebook, Messenger에서 바로 사용할 수 있으며, 이미지 생성과 실시간 검색도 지원합니다.",
    category: "chatbot",
    tags: ["무료", "Llama", "Meta", "Instagram", "WhatsApp"],
    url: "https://www.meta.ai",
    pricing: "free",
    plans: [
      { name: "무료", price: "완전 무료", features: ["Llama 4 모델", "이미지 생성", "SNS 앱 내 사용", "실시간 검색"], highlighted: true },
    ],
    featured: false,
    logo: "🌐",
    addedAt: "2024-02-03",
  },
  {
    slug: "mistral",
    name: "Mistral AI",
    tagline: "유럽의 강력한 오픈소스 LLM",
    description: "Mistral AI는 프랑스 스타트업이 개발한 고성능 오픈소스 LLM입니다. Mistral Large와 Mixtral 모델은 같은 크기 모델 중 최고 성능을 자랑하며, 매우 저렴한 API 가격으로 개발자들에게 인기입니다.",
    category: "chatbot",
    tags: ["오픈소스", "유럽", "API", "저가격", "Mixtral"],
    url: "https://mistral.ai",
    pricing: "freemium",
    plans: [
      { name: "Le Chat 무료", price: "무료", features: ["Mistral Large 사용", "웹 검색", "이미지 생성"] },
      { name: "API", price: "$0.07/M 토큰~", features: ["다양한 모델 선택", "초저가 가격", "OpenAI 호환"], highlighted: true },
    ],
    featured: false,
    logo: "🌬️",
    addedAt: "2024-02-04",
  },

  // ── 이미지 ────────────────────────────────────────────────────────────
  {
    slug: "flux",
    name: "FLUX.1",
    tagline: "현재 가장 사실적인 이미지 생성 AI",
    description: "FLUX.1은 Black Forest Labs가 개발한 차세대 이미지 생성 모델입니다. 사진처럼 사실적인 이미지 생성에서 Midjourney와 Stable Diffusion을 앞서며, 텍스트 렌더링도 매우 우수합니다. 오픈소스로 다양한 플랫폼에서 사용 가능합니다.",
    category: "image",
    tags: ["사실적", "오픈소스", "고화질", "텍스트 렌더링"],
    url: "https://blackforestlabs.ai",
    pricing: "freemium",
    plans: [
      { name: "무료(로컬)", price: "무료", features: ["FLUX.1 Schnell 오픈소스", "무제한 생성", "GPU 필요"] },
      { name: "API", price: "$0.003/이미지~", features: ["FLUX.1 Pro 접근", "빠른 생성", "고해상도"], highlighted: true },
    ],
    featured: false,
    logo: "⚡",
    addedAt: "2024-02-05",
  },
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    tagline: "상업적 사용 안전한 Adobe의 AI 이미지 생성",
    description: "Adobe Firefly는 Adobe가 개발한 AI 이미지 생성 도구로, 상업적 사용에 안전한 데이터셋으로 훈련됐습니다. Photoshop의 Generative Fill, Illustrator의 Generative Recolor 등 Adobe 앱과 깊이 통합됩니다.",
    category: "image",
    tags: ["Adobe", "상업적 사용", "Photoshop", "Illustrator", "안전"],
    url: "https://firefly.adobe.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 25 크레딧", "기본 이미지 생성", "워터마크 포함"] },
      { name: "Creative Cloud", price: "$54.99/월", features: ["월 1,000 크레딧", "Photoshop·Illustrator 통합", "상업적 사용"], highlighted: true },
    ],
    featured: false,
    logo: "🔥",
    addedAt: "2024-02-06",
  },
  {
    slug: "canva-ai",
    name: "Canva AI",
    tagline: "디자인 플랫폼에 통합된 AI 도구 모음",
    description: "Canva는 Magic Studio라는 AI 기능 모음을 제공합니다. Magic Write(글쓰기), Magic Design(디자인 자동생성), Magic Media(이미지·영상 생성), Background Remover 등 25개 이상의 AI 도구가 포함됩니다.",
    category: "design",
    tags: ["디자인", "템플릿", "이미지", "프레젠테이션", "SNS"],
    url: "https://www.canva.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["기본 템플릿", "AI 제한 사용", "5GB 저장"] },
      { name: "Pro", price: "$15/월", features: ["AI 도구 무제한", "1TB 저장", "브랜드 키트", "배경 제거 무제한"], highlighted: true },
      { name: "Teams", price: "$10/월·인", features: ["Pro 전체", "팀 협업", "최소 3명"] },
    ],
    featured: false,
    logo: "🎨",
    addedAt: "2024-02-07",
  },
  {
    slug: "dall-e-3",
    name: "DALL·E 3",
    tagline: "OpenAI의 고품질 이미지 생성 모델",
    description: "DALL·E 3는 OpenAI가 개발한 이미지 생성 AI로, 복잡한 프롬프트도 정확하게 이해해 고품질 이미지를 생성합니다. ChatGPT에 통합되어 있으며, API로도 사용 가능합니다.",
    category: "image",
    tags: ["OpenAI", "이미지 생성", "API", "ChatGPT 통합"],
    url: "https://openai.com/dall-e-3",
    pricing: "freemium",
    plans: [
      { name: "ChatGPT Plus", price: "$20/월", features: ["DALL·E 3 접근", "ChatGPT 통합", "고화질 이미지"], highlighted: true },
      { name: "API", price: "$0.04/이미지~", features: ["1024x1024 이미지", "HD 옵션", "상업적 사용"] },
    ],
    featured: false,
    logo: "🎭",
    addedAt: "2024-02-08",
  },

  // ── 코딩 ──────────────────────────────────────────────────────────────
  {
    slug: "windsurf",
    name: "Windsurf",
    tagline: "Cascade AI 에이전트가 내장된 코드 에디터",
    description: "Windsurf(구 Codeium)는 멀티 에이전트 AI 시스템인 Cascade를 탑재한 코드 에디터입니다. 코드베이스 전체를 이해하고 자율적으로 여러 파일을 수정하며, 웹 검색까지 결합해 복잡한 개발 작업을 자동화합니다.",
    category: "coding",
    tags: ["AI 에이전트", "코딩", "IDE", "Cascade", "자율 코딩"],
    url: "https://windsurf.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["Cascade 기본 사용", "자동완성 무제한", "기본 모델"] },
      { name: "Pro", price: "$15/월", features: ["Cascade 무제한", "GPT-4·Claude 접근", "우선 처리"], highlighted: true },
    ],
    featured: false,
    logo: "🌊",
    addedAt: "2024-02-09",
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    tagline: "프라이버시 우선 AI 코드 자동완성",
    description: "Tabnine은 기업용 AI 코드 자동완성 도구로, 로컬 또는 프라이빗 서버에서 실행 가능해 코드 유출 걱정이 없습니다. VS Code, IntelliJ 등 주요 IDE를 지원하며 팀 코드베이스를 학습해 개인화된 제안을 제공합니다.",
    category: "coding",
    tags: ["코딩", "프라이버시", "기업", "자동완성", "IDE"],
    url: "https://tabnine.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["기본 자동완성", "소규모 모델", "14일 Pro 체험"] },
      { name: "Pro", price: "$12/월", features: ["전체 라인 완성", "채팅 기능", "GPT-4 기반"], highlighted: true },
      { name: "Enterprise", price: "맞춤 요금", features: ["로컬 배포", "프라이빗 모델", "팀 커스터마이징"] },
    ],
    featured: false,
    logo: "🔒",
    addedAt: "2024-02-10",
  },
  {
    slug: "bolt",
    name: "Bolt.new",
    tagline: "브라우저에서 풀스택 앱을 즉시 생성·배포",
    description: "Bolt.new는 StackBlitz가 만든 AI 풀스택 개발 도구로, 프롬프트만으로 React, Next.js, Vue 등 웹앱을 생성하고 브라우저에서 즉시 실행·배포할 수 있습니다. 외부 패키지 설치, 환경변수 설정, 터미널 실행까지 완전 자동화됩니다.",
    category: "coding",
    tags: ["풀스택", "브라우저", "배포", "React", "Next.js"],
    url: "https://bolt.new",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["일 15만 토큰", "기본 프로젝트", "공개 배포"] },
      { name: "Pro", price: "$20/월", features: ["일 1,000만 토큰", "프라이빗 프로젝트", "맞춤 도메인"], highlighted: true },
    ],
    featured: false,
    logo: "⚡",
    addedAt: "2024-02-11",
  },
  {
    slug: "amazon-q",
    name: "Amazon Q Developer",
    tagline: "AWS 환경 최적화 AI 코딩 어시스턴트",
    description: "Amazon Q Developer는 AWS가 개발한 AI 코딩 어시스턴트로, AWS 서비스와 깊이 통합됩니다. 코드 자동완성, 보안 취약점 탐지, 코드 변환(Java 마이그레이션 등), 인프라 추천 기능을 제공합니다.",
    category: "coding",
    tags: ["AWS", "클라우드", "보안", "코딩", "인프라"],
    url: "https://aws.amazon.com/q/developer",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 50회 채팅", "코드 자동완성", "IDE 플러그인"] },
      { name: "Pro", price: "$19/월·인", features: ["무제한 채팅", "코드 변환", "엔터프라이즈 보안"], highlighted: true },
    ],
    featured: false,
    logo: "☁️",
    addedAt: "2024-02-12",
  },

  // ── 글쓰기 ────────────────────────────────────────────────────────────
  {
    slug: "jasper",
    name: "Jasper",
    tagline: "마케팅 팀을 위한 AI 콘텐츠 플랫폼",
    description: "Jasper는 마케팅 콘텐츠 생성에 특화된 AI 플랫폼입니다. 브랜드 보이스를 학습해 일관된 톤으로 블로그, 광고, 이메일, SNS 콘텐츠를 생성합니다. SEO 최적화와 팀 협업 기능도 포함됩니다.",
    category: "writing",
    tags: ["마케팅", "브랜드", "SEO", "블로그", "광고"],
    url: "https://www.jasper.ai",
    pricing: "paid",
    plans: [
      { name: "Creator", price: "$49/월", features: ["1개 워크스페이스", "AI 글쓰기 무제한", "SEO 기능"], highlighted: true },
      { name: "Pro", price: "$69/월", features: ["5개 워크스페이스", "팀 협업", "브랜드 보이스"] },
      { name: "Business", price: "맞춤 요금", features: ["무제한 워크스페이스", "API 접근", "전담 지원"] },
    ],
    featured: false,
    logo: "🪄",
    addedAt: "2024-02-13",
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    tagline: "AI 기반 문법 교정 및 글쓰기 개선",
    description: "Grammarly는 문법, 맞춤법, 명확성, 문체를 실시간으로 교정하는 AI 글쓰기 어시스턴트입니다. 브라우저 확장, MS Word, Gmail 등에서 동작하며, 2024년 생성형 AI 기능이 대폭 강화됐습니다.",
    category: "writing",
    tags: ["문법", "교정", "영어", "브라우저 확장", "이메일"],
    url: "https://www.grammarly.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["기본 문법 교정", "맞춤법 검사", "Chrome 확장"] },
      { name: "Premium", price: "$12/월", features: ["고급 문체 제안", "표절 탐지", "AI 글쓰기 지원"], highlighted: true },
      { name: "Business", price: "$15/월·인", features: ["팀 관리", "스타일 가이드", "우선 지원"] },
    ],
    featured: false,
    logo: "✅",
    addedAt: "2024-02-14",
  },
  {
    slug: "quillbot",
    name: "QuillBot",
    tagline: "AI 패러프레이징 및 요약 도구",
    description: "QuillBot은 텍스트를 다양한 스타일로 패러프레이징(재작성)하는 AI 도구입니다. 학술, 창작, 간결, 공식 등 9가지 모드를 지원하며, 요약, 문법 교정, 표절 탐지, 번역 기능도 제공합니다.",
    category: "writing",
    tags: ["패러프레이징", "요약", "번역", "학술", "교정"],
    url: "https://quillbot.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["125단어 패러프레이징", "3가지 모드", "기본 요약"] },
      { name: "Premium", price: "$10/월", features: ["무제한 패러프레이징", "9가지 모드", "표절 탐지 10회/월"], highlighted: true },
    ],
    featured: false,
    logo: "🖊️",
    addedAt: "2024-02-15",
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    tagline: "SEO 최적화 AI 글쓰기 도구",
    description: "Writesonic은 블로그, 광고, 이메일, 제품 설명 등 다양한 마케팅 콘텐츠를 AI로 생성합니다. Surfer SEO와 연동해 검색엔진 최적화된 콘텐츠를 작성할 수 있으며, AI 챗봇 빌더도 포함됩니다.",
    category: "writing",
    tags: ["SEO", "블로그", "광고", "이메일", "콘텐츠"],
    url: "https://writesonic.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 10,000 단어", "100+ 템플릿", "GPT-4 기본"] },
      { name: "Individual", price: "$20/월", features: ["월 무제한 단어", "Surfer SEO 연동", "AI 챗봇"], highlighted: true },
    ],
    featured: false,
    logo: "📄",
    addedAt: "2024-02-16",
  },

  // ── 생산성 ────────────────────────────────────────────────────────────
  {
    slug: "gamma",
    name: "Gamma",
    tagline: "AI로 프레젠테이션·문서·웹페이지 즉시 생성",
    description: "Gamma는 텍스트 프롬프트만으로 프레젠테이션, 문서, 웹페이지를 자동 생성하는 AI 도구입니다. 7,000만 명 이상이 사용하며, 기존 PPT 파일을 업로드해 AI로 리디자인하거나 웹으로 공유할 수도 있습니다.",
    category: "productivity",
    tags: ["프레젠테이션", "슬라이드", "문서", "웹페이지", "PPT"],
    url: "https://gamma.app",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["400 AI 크레딧", "무제한 덱", "Gamma 브랜딩"] },
      { name: "Plus", price: "$10/월", features: ["무제한 AI 크레딧", "브랜딩 제거", "Analytics"], highlighted: true },
      { name: "Pro", price: "$20/월", features: ["Plus 전체", "우선 지원", "맞춤 도메인"] },
    ],
    featured: false,
    logo: "📊",
    addedAt: "2024-02-17",
  },
  {
    slug: "zapier",
    name: "Zapier",
    tagline: "8,000개 앱을 연결하는 AI 자동화 플랫폼",
    description: "Zapier는 코딩 없이 앱과 서비스를 자동화하는 플랫폼입니다. Gmail, Slack, Notion, Salesforce 등 8,000개 이상의 앱을 연결할 수 있으며, AI 에이전트 기능으로 복잡한 워크플로우도 자동화합니다.",
    category: "automation",
    tags: ["자동화", "연동", "워크플로우", "노코드", "API"],
    url: "https://zapier.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 100 Task", "Zap 5개", "기본 앱 연동"] },
      { name: "Starter", price: "$19.99/월", features: ["월 750 Task", "Zap 20개", "멀티스텝 Zap"], highlighted: true },
      { name: "Professional", price: "$49/월", features: ["월 2,000 Task", "무제한 Zap", "AI 파워 기능"] },
    ],
    featured: false,
    logo: "⚡",
    addedAt: "2024-02-18",
  },
  {
    slug: "n8n",
    name: "n8n",
    tagline: "오픈소스 셀프호스팅 워크플로우 자동화",
    description: "n8n은 400개 이상의 앱을 연결할 수 있는 오픈소스 자동화 도구입니다. Zapier와 달리 셀프호스팅이 가능해 완전한 데이터 제어권을 가지며, AI 에이전트·RAG 파이프라인 구축에도 활용됩니다.",
    category: "automation",
    tags: ["오픈소스", "셀프호스팅", "자동화", "AI 에이전트", "RAG"],
    url: "https://n8n.io",
    pricing: "freemium",
    plans: [
      { name: "셀프호스팅", price: "무료", features: ["완전 무료", "400+ 연동", "무제한 워크플로우"], highlighted: true },
      { name: "Cloud Starter", price: "$24/월", features: ["5,000 실행/월", "관리형 호스팅", "24시간 지원"] },
    ],
    featured: false,
    logo: "🔄",
    addedAt: "2024-02-19",
  },
  {
    slug: "loom",
    name: "Loom",
    tagline: "화면 녹화에 AI 자막·요약이 더해진 영상 메시지",
    description: "Loom은 화면과 카메라를 동시에 녹화해 영상 메시지를 보내는 도구입니다. AI가 자동으로 자막을 생성하고 핵심 내용을 요약해주며, Slack·Notion·Jira와 연동됩니다. 원격 팀의 비동기 소통에 특히 유용합니다.",
    category: "productivity",
    tags: ["화면 녹화", "영상 메시지", "자막", "요약", "원격 협업"],
    url: "https://www.loom.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["최대 25개 영상", "5분 제한", "AI 자막"] },
      { name: "Business", price: "$12.50/월", features: ["무제한 영상", "시간 제한 없음", "AI 요약 무제한"], highlighted: true },
    ],
    featured: false,
    logo: "🎬",
    addedAt: "2024-02-20",
  },
  {
    slug: "notebooklm",
    name: "NotebookLM",
    tagline: "구글의 AI 리서치 노트, 문서를 팟캐스트로",
    description: "NotebookLM은 Google이 개발한 AI 리서치 도구로, PDF·문서·유튜브를 업로드하면 AI가 내용을 분석해 Q&A, 요약, 학습 가이드를 생성합니다. Audio Overview 기능으로 문서를 팟캐스트 형식의 대화로 변환하는 것이 특징입니다.",
    category: "research",
    tags: ["리서치", "구글", "문서 분석", "팟캐스트", "학습"],
    url: "https://notebooklm.google.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["노트북 100개", "소스 50개/노트북", "Audio Overview"] },
      { name: "Plus", price: "Google One AI Premium 포함", features: ["Gemini Advanced 포함", "소스 300개/노트북", "우선 접근"], highlighted: true },
    ],
    featured: false,
    logo: "📓",
    addedAt: "2024-02-21",
  },

  // ── 비디오 ────────────────────────────────────────────────────────────
  {
    slug: "pika",
    name: "Pika",
    tagline: "이미지·텍스트로 영상을 만드는 AI",
    description: "Pika는 텍스트 설명이나 이미지로 짧은 동영상을 생성하는 AI 도구입니다. Scene Ingredients 기능으로 특정 캐릭터·사물을 지정해 일관성 있는 영상을 만들 수 있으며, 기존 영상 스타일 변환도 지원합니다.",
    category: "video",
    tags: ["동영상 생성", "텍스트-비디오", "이미지-비디오", "스타일 변환"],
    url: "https://pika.art",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 250 크레딧", "워터마크 포함", "기본 생성"] },
      { name: "Basic", price: "$8/월", features: ["월 700 크레딧", "워터마크 없음", "HD 영상"], highlighted: true },
      { name: "Standard", price: "$28/월", features: ["월 2,000 크레딧", "4K 영상", "우선 처리"] },
    ],
    featured: false,
    logo: "🎞️",
    addedAt: "2024-02-22",
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    tagline: "AI 아바타로 160개 언어 교육·마케팅 영상 제작",
    description: "Synthesia는 AI 아바타를 활용해 전문 영상을 제작하는 플랫폼입니다. 텍스트만 입력하면 160개 이상 언어로 말하는 아바타 영상이 완성됩니다. 교육 콘텐츠, 사내 교육, 마케팅 영상 제작에 가장 많이 사용됩니다.",
    category: "video",
    tags: ["AI 아바타", "교육", "다국어", "마케팅", "기업"],
    url: "https://synthesia.io",
    pricing: "paid",
    plans: [
      { name: "Starter", price: "$29/월", features: ["월 10분 영상", "아바타 125개", "160개 언어"] },
      { name: "Creator", price: "$89/월", features: ["월 30분 영상", "커스텀 아바타", "브랜드 키트"], highlighted: true },
      { name: "Enterprise", price: "맞춤 요금", features: ["무제한 영상", "API 접근", "SSO"] },
    ],
    featured: false,
    logo: "🎭",
    addedAt: "2024-02-23",
  },
  {
    slug: "d-id",
    name: "D-ID",
    tagline: "사진 한 장으로 말하는 아바타 영상 생성",
    description: "D-ID는 사진 한 장을 업로드하면 실제로 말하고 움직이는 아바타 영상을 만들어주는 AI 플랫폼입니다. 자연스러운 립싱크와 표정이 특징이며, API를 통해 대규모 개인화 영상 제작에 활용됩니다.",
    category: "video",
    tags: ["아바타", "립싱크", "개인화", "API", "사진-영상"],
    url: "https://www.d-id.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["영상 5개 체험", "기본 아바타", "워터마크"] },
      { name: "Lite", price: "$5.9/월", features: ["월 10분 영상", "워터마크 없음", "HD 영상"], highlighted: true },
      { name: "Pro", price: "$49.9/월", features: ["월 40분 영상", "커스텀 아바타", "API 접근"] },
    ],
    featured: false,
    logo: "👤",
    addedAt: "2024-02-24",
  },
  {
    slug: "invideo-ai",
    name: "InVideo AI",
    tagline: "텍스트 프롬프트로 완성된 YouTube 영상 생성",
    description: "InVideo AI는 텍스트 스크립트나 주제만 입력하면 스톡 영상, AI 목소리, 자막, 배경음악이 포함된 완성된 영상을 자동 생성합니다. YouTube, TikTok, Instagram 콘텐츠 제작에 최적화되어 있습니다.",
    category: "video",
    tags: ["YouTube", "TikTok", "스톡 영상", "자동 편집", "SNS"],
    url: "https://invideo.io",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 10분 영상", "워터마크", "10GB 저장"] },
      { name: "Plus", price: "$25/월", features: ["월 50분 영상", "워터마크 없음", "80 AI 자막"], highlighted: true },
      { name: "Max", price: "$60/월", features: ["월 200분 영상", "4K 내보내기", "AI 음성 복제"] },
    ],
    featured: false,
    logo: "📹",
    addedAt: "2024-02-25",
  },

  // ── 오디오 ────────────────────────────────────────────────────────────
  {
    slug: "play-ht",
    name: "PlayHT",
    tagline: "800개 이상 AI 음성으로 최고 품질 TTS",
    description: "PlayHT는 800개 이상의 AI 음성과 142개 언어를 지원하는 텍스트-음성 변환 플랫폼입니다. 감정 표현, 속도 조절, 목소리 복제 기능을 제공하며, 팟캐스트·오디오북·IVR 시스템 제작에 많이 활용됩니다.",
    category: "audio",
    tags: ["TTS", "음성 합성", "목소리 복제", "팟캐스트", "다국어"],
    url: "https://play.ht",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 12,500자", "100개 음성", "스트리밍 API"] },
      { name: "Creator", price: "$31.2/월", features: ["월 500,000자", "800개 음성", "상업적 사용"], highlighted: true },
      { name: "Unlimited", price: "$99/월", features: ["무제한", "목소리 복제 무제한", "API 무제한"] },
    ],
    featured: false,
    logo: "🎧",
    addedAt: "2024-02-26",
  },
  {
    slug: "murf-ai",
    name: "Murf AI",
    tagline: "스튜디오 품질의 AI 보이스오버",
    description: "Murf AI는 자연스러운 AI 보이스오버를 생성하는 플랫폼입니다. 120개 이상의 음성, 20개 언어를 지원하며 음정, 속도, 감정을 세밀하게 조절할 수 있습니다. 영상에 직접 음성을 합성하는 기능도 제공합니다.",
    category: "audio",
    tags: ["보이스오버", "나레이션", "광고", "영상", "다국어"],
    url: "https://murf.ai",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["10분 음성 생성", "60개 음성", "워터마크"] },
      { name: "Creator", price: "$29/월", features: ["2시간 음성/월", "120개 음성", "상업적 사용"], highlighted: true },
      { name: "Business", price: "$99/월", features: ["무제한 음성", "목소리 복제", "팀 공유"] },
    ],
    featured: false,
    logo: "🎤",
    addedAt: "2024-02-27",
  },
  {
    slug: "soundraw",
    name: "Soundraw",
    tagline: "저작권 걱정 없는 AI 배경음악 생성",
    description: "Soundraw는 분위기, 장르, 길이를 지정하면 저작권 없는 오리지널 음악을 즉시 생성하는 AI 도구입니다. 유튜브, SNS, 게임, 광고에 사용 가능하며, 생성된 음악은 상업적 사용이 허가됩니다.",
    category: "audio",
    tags: ["배경음악", "BGM", "저작권 무료", "YouTube", "게임"],
    url: "https://soundraw.io",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["음악 생성 가능", "다운로드 불가", "미리 듣기"] },
      { name: "Creator", price: "$16.99/월", features: ["무제한 다운로드", "상업적 사용", "저작권 보호"], highlighted: true },
    ],
    featured: false,
    logo: "🎶",
    addedAt: "2024-02-28",
  },

  // ── 리서치 ────────────────────────────────────────────────────────────
  {
    slug: "consensus",
    name: "Consensus",
    tagline: "AI가 학술 논문에서 직접 답을 찾아주는 검색 엔진",
    description: "Consensus는 200개 이상의 학술 데이터베이스에서 피어리뷰 논문을 검색하고 AI가 핵심 내용을 요약해주는 리서치 도구입니다. 논문의 주요 결론, 방법론, 통계를 빠르게 파악할 수 있습니다.",
    category: "research",
    tags: ["학술", "논문", "리서치", "피어리뷰", "의학"],
    url: "https://consensus.app",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 20회 AI 검색", "기본 요약", "논문 링크"] },
      { name: "Premium", price: "$9.99/월", features: ["무제한 AI 검색", "상세 요약", "논문 저장"], highlighted: true },
    ],
    featured: false,
    logo: "📚",
    addedAt: "2024-03-01",
  },
  {
    slug: "you-com",
    name: "You.com",
    tagline: "AI 검색과 생성이 결합된 차세대 검색 엔진",
    description: "You.com은 AI 검색과 생성 기능을 결합한 검색 엔진입니다. YouChat으로 대화하면서 검색하고, YouCode로 코드를 작성하며, YouWrite로 글쓰기를 할 수 있습니다. 개인 맞춤형 검색 결과와 광고 없는 경험이 특징입니다.",
    category: "research",
    tags: ["검색", "AI 검색", "광고 없음", "코딩", "글쓰기"],
    url: "https://you.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["AI 검색 무제한", "YouChat 기본", "광고 최소화"] },
      { name: "YouPro", price: "$15/월", features: ["GPT-4·Claude 선택", "이미지 생성", "광고 없음"], highlighted: true },
    ],
    featured: false,
    logo: "🔮",
    addedAt: "2024-03-02",
  },
  {
    slug: "elicit",
    name: "Elicit",
    tagline: "AI가 논문 데이터를 표로 정리해주는 리서치 도구",
    description: "Elicit은 학술 리서치를 자동화하는 AI 도구입니다. 연구 질문을 입력하면 관련 논문을 찾고, 방법론·결과·한계를 테이블 형식으로 정리해줍니다. 체계적 문헌 고찰(Systematic Review)에 특히 유용합니다.",
    category: "research",
    tags: ["학술", "논문 정리", "체계적 고찰", "데이터 추출", "리뷰"],
    url: "https://elicit.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["월 5,000 크레딧", "기본 논문 검색", "데이터 추출"] },
      { name: "Plus", price: "$12/월", features: ["월 12,000 크레딧", "전체 텍스트 분석", "PDF 업로드"], highlighted: true },
    ],
    featured: false,
    logo: "🔬",
    addedAt: "2024-03-03",
  },

  // ── 디자인 ────────────────────────────────────────────────────────────
  {
    slug: "framer-ai",
    name: "Framer AI",
    tagline: "텍스트 프롬프트로 웹사이트를 즉시 생성",
    description: "Framer는 프롬프트만 입력하면 완성된 웹사이트를 자동 생성하는 AI 웹 빌더입니다. 디자인 시스템, 애니메이션, CMS까지 포함된 전문적인 사이트를 코딩 없이 만들 수 있으며, 실시간 협업도 지원합니다.",
    category: "design",
    tags: ["웹사이트", "노코드", "디자인", "AI 생성", "애니메이션"],
    url: "https://www.framer.com",
    pricing: "freemium",
    plans: [
      { name: "무료", price: "무료", features: ["사이트 1개", "Framer 도메인", "AI 기능 체험"] },
      { name: "Mini", price: "$5/월", features: ["맞춤 도메인", "AI 페이지 무제한", "SEO"], highlighted: true },
      { name: "Basic", price: "$15/월", features: ["CMS 1,000개", "패스워드 보호", "분석"] },
    ],
    featured: false,
    logo: "🌐",
    addedAt: "2024-03-04",
  },
  {
    slug: "beautiful-ai",
    name: "Beautiful.ai",
    tagline: "AI가 자동 정렬하는 스마트 프레젠테이션",
    description: "Beautiful.ai는 콘텐츠를 추가하면 AI가 자동으로 레이아웃을 최적화하는 프레젠테이션 도구입니다. 슬라이드 간 일관된 디자인을 유지하며, 템플릿 기반으로 빠르게 전문적인 자료를 만들 수 있습니다.",
    category: "design",
    tags: ["프레젠테이션", "슬라이드", "자동 레이아웃", "팀 협업", "브랜딩"],
    url: "https://www.beautiful.ai",
    pricing: "paid",
    plans: [
      { name: "Pro", price: "$12/월", features: ["슬라이드 무제한", "AI 디자인", "PDF 내보내기"], highlighted: true },
      { name: "Team", price: "$40/월", features: ["팀 협업", "브랜드 키트", "관리자 설정"] },
    ],
    featured: false,
    logo: "✨",
    addedAt: "2024-03-05",
  },
];

export function getToolsByCategory(category: string): Tool[] {
  if (category === "all") return TOOLS;
  return TOOLS.filter((t) => t.category === category);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.tagline.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q))
  );
}

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug);
}

export const PRICING_LABELS: Record<PricingType, string> = {
  free: "무료",
  freemium: "무료/유료",
  paid: "유료",
};

export const PRICING_COLORS: Record<PricingType, string> = {
  free: "bg-green-100 text-green-700",
  freemium: "bg-blue-100 text-blue-700",
  paid: "bg-orange-100 text-orange-700",
};
